- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Cleanup
      shell: docker ps -aq --filter name="calculator" | xargs docker stop | xargs docker rm
    - name: Pull docker image
      shell: docker pull sarthakharne2262/calculator:latest
    - name: Run docker image
      shell: docker run -i -t  --name calculator -d sarthakharne2262/calculator:latest